### Recuperar todos los tips
GET http://localhost:8080/tips

### Recuperar un tip por id
GET http://localhost:8080/tips/6580e09ba31ed450272f3fe7



### Crear un tip con POST
POST http://localhost:8080/tips
Content-Type: application/json

{
  "tipster": "El Profesor",
  "date": "2023-12-22",
  "name": "Craiova crear apuesta",
  "status": "failed",
  "spent": 9,
  "potentialReturn": 14,
  "type": "football",
  "selections": [{"name": "Ambos marcan y gana craiova", "status": "failed"}]
}

### Actualizar un tip
PATCH http://localhost:8080/tips/6580e09ba31ed450272f3fe7
Content-Type: application/json

{ 
  "spent": 11
}

### Borrar un tip
DELETE http://localhost:8080/tips/6589d88e169f4d46d90367fd
